In [5]:
import pandas as pd

In [6]:
df = pd.read_csv("dirty_instacart_sales.csv")

In [7]:
data = df.copy()

In [8]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [13]:
data.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='str')

In [17]:
data.isna().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [19]:
data.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [10]:
df["Quantity"].value_counts()

Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64

In [11]:
df["Quantity"].isna().sum()

np.int64(138)

In [15]:
# data["Quantity"] = pd.to_numeric(data["Quantity"])
# change each text to NAN

# data["Quantity"].value_counts()
data["Quantity"] = pd.to_numeric(data["Quantity"], errors= "coerce")

In [12]:
data["Quantity"].value_counts()

Quantity
5          2013
2          1974
4          1863
3          1849
1          1822
UNKNOWN     171
ERROR       170
Name: count, dtype: int64

In [16]:
data["Quantity"].isna().sum()

np.int64(479)

In [83]:
mean_quantity = data["Quantity"].mean()
# data["Quantity"] = data["Quantity"].fillna(mean_quantity)
mean_quantity = int(mean_quantity)
mean_quantity

3

In [84]:
 
mean_quantity = int(mean_quantity)

data["Quantity"] = data["Quantity"].fillna(mean_quantity)

In [59]:
mean_quantity

3

In [60]:
data["Quantity"].value_counts()

Quantity
3.0    2328
5.0    2013
2.0    1974
4.0    1863
1.0    1822
Name: count, dtype: int64

In [61]:
data["Quantity"].isna().sum()

np.int64(0)

In [62]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [65]:
data["Price Per Unit"].value_counts()

Price Per Unit
3.0        2429
4.0        2331
2.0        1227
5.0        1204
1.0        1143
1.5        1133
ERROR       190
UNKNOWN     164
Name: count, dtype: int64

In [85]:
data["Price Per Unit"] = pd.to_numeric(data["Price Per Unit"], errors="coerce")

In [86]:
data["Price Per Unit"].value_counts()

Price Per Unit
3.0    2096
4.0    2017
2.0    1069
5.0    1035
1.0     976
1.5     965
Name: count, dtype: int64

In [87]:
mean_price = data["Price Per Unit"].mean()
# data["Price Per Unit"] = data["Price Per Unit"].fillna(data["Price Per Unit"].mean())
mean_price

np.float64(2.9532360872762933)

In [88]:
mean_price = int(mean_price)
mean_price

2

In [89]:
data["Price Per Unit"] = data["Price Per Unit"].fillna(mean_price)

In [90]:
data["Price Per Unit"].value_counts()

Price Per Unit
3.0    2096
4.0    2017
2.0    1524
5.0    1035
1.0     976
1.5     965
Name: count, dtype: int64

In [74]:
data

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3.0,2.0,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,2.0,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [91]:
data["Total Spent"].value_counts()

Total Spent
8.0     1017
6.0      840
12.0     811
4.0      797
3.0      795
20.0     644
15.0     614
10.0     455
2.0      432
9.0      413
5.0      400
16.0     383
25.0     229
7.5      210
4.5      195
1.0      194
1.5      184
Name: count, dtype: int64

In [24]:
data["Total Spent"] =  pd.to_numeric(data["Total Spent"], errors="coerce")

In [92]:
data["Total Spent"].value_counts()

Total Spent
8.0     1017
6.0      840
12.0     811
4.0      797
3.0      795
20.0     644
15.0     614
10.0     455
2.0      432
9.0      413
5.0      400
16.0     383
25.0     229
7.5      210
4.5      195
1.0      194
1.5      184
Name: count, dtype: int64

In [93]:
mean_spent =int( data["Total Spent"].mean()
)

In [ ]:
mean_spent

8

In [94]:
data["Total Spent"] = data["Total Spent"].fillna(mean_spent)
# data["Total Spent"].isna().sum()

In [95]:
data["Total Spent"].isna().sum()

np.int64(0)

In [36]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Total Spent
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0
2,TXN_4271903,Cookie,4.0,1.0,8.0,Credit Card,In-store,2023-07-19,8.0
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,10.0
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0

In [37]:
data["Transaction Date"].value_counts()

Transaction Date
UNKNOWN       159
ERROR         142
2023-02-06     40
2023-06-16     40
2023-03-13     39
             ...
2023-09-24     15
2023-07-30     15
2023-03-11     14
2023-07-22     14
2023-02-17     14
Name: count, Length: 367, dtype: int64

In [38]:
import numpy as np
data["Transaction Date"] = data["Transaction Date"].replace(["UNKNOWN", "ERROR"], np.nan)

In [39]:
data["Transaction Date"].value_counts()

Transaction Date
2023-02-06    40
2023-06-16    40
2023-03-13    39
2023-07-21    39
2023-07-24    39
              ..
2023-09-24    15
2023-07-30    15
2023-03-11    14
2023-07-22    14
2023-02-17    14
Name: count, Length: 365, dtype: int64

In [40]:
data["Transaction Date"].isna().sum()

np.int64(460)

In [41]:
data["Transaction Date"].dtype

In [43]:
data["Transaction Date"] = pd.to_datetime(data["Transaction Date"], errors="coerce")
# errors="coerce" changes any non date equivakent vakue to NaT, equivalent to NaN

In [44]:
data["Transaction Date"].dtype

dtype('<M8[us]')

In [45]:
data["Transaction Date"].isna().sum()

np.int64(460)

In [47]:
data = data.dropna(subset=["Transaction Date"])

In [48]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date,Total Spent
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08,4.0
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16,12.0
2,TXN_4271903,Cookie,4.0,1.0,8.0,Credit Card,In-store,2023-07-19,8.0
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27,10.0
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11,4.0

In [50]:
data.drop(columns=['Total  Spent'], inplace=True)

In [52]:
data["Item"].isna().sum()

np.int64(315)

In [53]:
data["Item"].value_counts()

Item
Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
UNKNOWN      329
ERROR        283
Name: count, dtype: int64

In [56]:
data["Item"]=data["Item"].replace(["UNKNOWN", "ERROR"], np.nan )

In [57]:
data["Item"].value_counts()

Item
Juice       1124
Coffee      1123
Salad       1099
Cake        1082
Sandwich    1075
Smoothie    1048
Cookie      1035
Tea         1027
Name: count, dtype: int64

In [58]:
data["Item"].isna().sum()

np.int64(927)

In [59]:
print(data.shape)
print(data["Item"].isna().sum())

(9540, 8)
927

In [63]:
data['Item']=data['Item'].dropna()
data['Item'].isna().sum()

np.int64(927)

In [61]:
data['Item'].isna().sum()

np.int64(927)

In [64]:
data = data.dropna(subset=['Item'])

In [65]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [66]:
data["Payment Method"].value_counts()

Payment Method
Digital Wallet    1980
Cash              1956
Credit Card       1949
ERROR              276
UNKNOWN            249
Name: count, dtype: int64

In [68]:
data["Payment Method"]=data["Payment Method"].replace(['ERROR','UNKNOWN'], np.nan)

In [70]:
data["Payment Method"] = data["Payment Method"].fillna('Missing')

In [71]:
data.head()

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Missing,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [73]:
data['Location'] = data['Location'].replace(['UNKNOWN','ERROR'], np.nan)

In [78]:
# data['Location'] = data['Location'].fillna()
df["Location"].value_counts()

Location
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64

In [77]:
data["Location"].isna().sum()

np.int64(3423)

In [80]:
data["Location"] = data["Location"].fillna('Missing')

In [81]:
data

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,8.0,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,Missing,Missing,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9993,TXN_4766549,Smoothie,2.0,4.0,8.0,Cash,Missing,2023-10-20
9995,TXN_7672686,Coffee,2.0,2.0,4.0,Missing,Missing,2023-08-30
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,Missing,2023-03-02
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,Missing,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-store,2023-11-07

In [96]:
data.isna().sum()

Transaction ID      0
Item                0
Quantity            0
Price Per Unit      0
Total Spent         0
Payment Method      0
Location            0
Transaction Date    0
dtype: int64

In [98]:
data.shape

(8613, 8)